name: flutter_klipper
description: klipper Flutter application.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flt_im_plugin:
    git: https://github.com/coscx/lat.git
  flutter_2d_amap:
    git: https://github.com/coscx/flutter_2d_amap.git
  umeng_analytics_with_push:
    git: https://github.com/coscx/umeng_push.git
  date_time_picker:
    git:
      url: https://github.com/DavidHDJ/date_time_picker.git
      ref: 2.1.1
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons.git
  another_xlider: ^1.1.2
  adaptive_action_sheet: ^2.0.1
  badges: ^3.0.2
  bot_toast: ^4.0.2
  cupertino_icons: ^1.0.4
  cookie_jar: ^3.0.1
  crypto: ^3.0.1
  connectivity: ^3.0.6 #网络状态
  cool_dropdown: ^1.4.2
  custom_pop_up_menu: ^1.2.4
  direct_select_flutter: ^1.1.1
  dio: ^5.0.2
  dio_cookie_manager: ^2.0.0
  device_info: ^2.0.3
  dropdown_search: ^2.0.1
  dots_indicator: 2.1.2
  encrypt: ^5.0.1
  event_bus: ^2.0.0
  equatable: ^2.0.3
  extended_image: ^8.1.0
  emoji_picker_flutter: ^1.3.0
  enum_to_string: ^2.0.1
  flutter_spinkit: ^5.1.0 #loading
  flutter_markdown: ^0.6.9 #NO
  flutter_star: ^1.0.2 # 星星组件
  flutter_app_update: ^1.0.5
  flex_color_scheme: ^7.0.4
  #flutter_local_notifications: ^9.4.0 #NO
  card_swiper: ^2.0.4
  flare_flutter: ^3.0.2
  flutter_image_compress: ^1.1.0
  flutter_picker: ^2.0.3
  flutter_pickers: ^2.1.9
  form_builder_validators: ^9.0.0
  fluwx_no_pay: ^3.9.0
  flutter_screenutil: ^5.8.4
  fluttertoast: ^8.0.9
  flutter_easyloading: ^3.0.5
  flutter_cache_manager: ^3.3.0
  flutter_svg: ^1.0.3
  flutter_smart_dialog: ^4.5.3+7
  flutter_slidable: ^2.0.0
  get: ^4.6.5
  getwidget: ^2.0.5
  group_radio_button: ^1.2.0
  http: ^1.1.0
  hooks_riverpod: ^2.3.2
  intl: ^0.18.0
  image_gallery_saver: ^1.7.1
  image_cropper: ^5.0.0
  just_audio: ^0.9.34
  just_bottom_sheet: ^1.3.0
  json_rpc_2: ^3.0.2
  flutter_keyboard_visibility: ^5.3.0
  loading_animations: ^2.2.0
  lottie: ^2.3.0
  left_scroll_actions: ^2.1.0
  logger: ^1.1.0
  lpinyin: ^2.0.2
  multi_image_picker: ^4.8.1
  menu_button: ^1.4.2+1
  multiselect_scope: ^0.2.0
  modal_bottom_sheet: ^3.0.0-pre
  media_asset_utils: ^0.1.0 #鲁班压缩
  overlay_support: ^1.2.1
  pull_to_refresh_flutter3: ^2.0.1
  package_info: ^2.0.2
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  qr_flutter: ^4.0.0
  record: ^4.4.4
  refresh_loadmore: ^2.0.5
  shared_preferences: ^2.0.13
  share: ^2.0.4
  sentry: ^7.9.0
  sqflite: ^2.0.2 #数据库
  select_form_field: ^2.2.0
  soundpool: ^2.3.0
  syncfusion_flutter_sliders: ^22.1.34
  syncfusion_flutter_barcodes: ^22.1.34
  swipe_image_gallery: ^0.5.1
  state_notifier: ^0.7.2+1
  toggle_rotate: ^1.0.1
  tab_indicator_styler: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.20 # url
  uuid: ^3.0.6
  video_player: ^2.5.1
  video_thumbnail: ^0.5.3
  vibration: ^1.7.4-nullsafety.0
  w_popup_menu: ^1.0.0
  webview_flutter: ^3.0.2
  wechat_assets_picker: ^8.7.0
  wechat_camera_picker: ^4.0.1
  web_socket_channel: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/packages/images/
    - assets/packages/lottie_flutter/
    - assets/images/default/
    - assets/images/icon/
    - assets/images/login/
    - assets/images/figure/
    - assets/images/ckt/
    - assets/images/friend/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfonterp.ttf
    - family: TolyIcon
      fonts:
        - asset: assets/fonts/iconfont.ttf